/* Generated By:JavaCC: Do not edit this line. JenaRulesJavaccConstants.java */
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */
package org.seaborne.jena.shacl_rules.lang.parser.jena_rules.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JenaRulesJavaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int BOM = 9;
  /** RegularExpression Id. */
  int IRIref = 10;
  /** RegularExpression Id. */
  int PNAME_NS = 11;
  /** RegularExpression Id. */
  int PNAME_LN = 12;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 13;
  /** RegularExpression Id. */
  int VAR1 = 14;
  /** RegularExpression Id. */
  int VAR2 = 15;
  /** RegularExpression Id. */
  int DOLLAR = 16;
  /** RegularExpression Id. */
  int LANG_DIR = 17;
  /** RegularExpression Id. */
  int A2Z = 18;
  /** RegularExpression Id. */
  int A2ZN = 19;
  /** RegularExpression Id. */
  int KW_A = 20;
  /** RegularExpression Id. */
  int RULE = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int TUPLE = 23;
  /** RegularExpression Id. */
  int DATA = 24;
  /** RegularExpression Id. */
  int INFER = 25;
  /** RegularExpression Id. */
  int TRANSITIVE = 26;
  /** RegularExpression Id. */
  int SYMMETRIC = 27;
  /** RegularExpression Id. */
  int INVERSE = 28;
  /** RegularExpression Id. */
  int IMPORTS = 29;
  /** RegularExpression Id. */
  int BASE = 30;
  /** RegularExpression Id. */
  int PREFIX = 31;
  /** RegularExpression Id. */
  int VERSION = 32;
  /** RegularExpression Id. */
  int WHERE = 33;
  /** RegularExpression Id. */
  int BIND = 34;
  /** RegularExpression Id. */
  int AS = 35;
  /** RegularExpression Id. */
  int LET = 36;
  /** RegularExpression Id. */
  int ASSIGN = 37;
  /** RegularExpression Id. */
  int TRIPLE = 38;
  /** RegularExpression Id. */
  int IS_TRIPLE = 39;
  /** RegularExpression Id. */
  int SUBJECT = 40;
  /** RegularExpression Id. */
  int PREDICATE = 41;
  /** RegularExpression Id. */
  int OBJECT = 42;
  /** RegularExpression Id. */
  int EXISTS = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int FILTER = 45;
  /** RegularExpression Id. */
  int IN = 46;
  /** RegularExpression Id. */
  int IF = 47;
  /** RegularExpression Id. */
  int BNODE = 48;
  /** RegularExpression Id. */
  int IRI = 49;
  /** RegularExpression Id. */
  int URI = 50;
  /** RegularExpression Id. */
  int STR = 51;
  /** RegularExpression Id. */
  int STRLANG = 52;
  /** RegularExpression Id. */
  int STRLANGDIR = 53;
  /** RegularExpression Id. */
  int STRDT = 54;
  /** RegularExpression Id. */
  int DTYPE = 55;
  /** RegularExpression Id. */
  int LANG = 56;
  /** RegularExpression Id. */
  int LANGMATCHES = 57;
  /** RegularExpression Id. */
  int LANGDIR = 58;
  /** RegularExpression Id. */
  int IS_URI = 59;
  /** RegularExpression Id. */
  int IS_IRI = 60;
  /** RegularExpression Id. */
  int IS_BLANK = 61;
  /** RegularExpression Id. */
  int IS_LITERAL = 62;
  /** RegularExpression Id. */
  int IS_NUMERIC = 63;
  /** RegularExpression Id. */
  int HAS_LANG = 64;
  /** RegularExpression Id. */
  int HAS_LANGDIR = 65;
  /** RegularExpression Id. */
  int REGEX = 66;
  /** RegularExpression Id. */
  int SAME_TERM = 67;
  /** RegularExpression Id. */
  int SAME_VALUE = 68;
  /** RegularExpression Id. */
  int ABS = 69;
  /** RegularExpression Id. */
  int CEIL = 70;
  /** RegularExpression Id. */
  int FLOOR = 71;
  /** RegularExpression Id. */
  int ROUND = 72;
  /** RegularExpression Id. */
  int CONCAT = 73;
  /** RegularExpression Id. */
  int SUBSTR = 74;
  /** RegularExpression Id. */
  int STRLEN = 75;
  /** RegularExpression Id. */
  int REPLACE = 76;
  /** RegularExpression Id. */
  int UCASE = 77;
  /** RegularExpression Id. */
  int LCASE = 78;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 79;
  /** RegularExpression Id. */
  int CONTAINS = 80;
  /** RegularExpression Id. */
  int STRSTARTS = 81;
  /** RegularExpression Id. */
  int STRENDS = 82;
  /** RegularExpression Id. */
  int STRBEFORE = 83;
  /** RegularExpression Id. */
  int STRAFTER = 84;
  /** RegularExpression Id. */
  int YEAR = 85;
  /** RegularExpression Id. */
  int MONTH = 86;
  /** RegularExpression Id. */
  int DAY = 87;
  /** RegularExpression Id. */
  int HOURS = 88;
  /** RegularExpression Id. */
  int MINUTES = 89;
  /** RegularExpression Id. */
  int SECONDS = 90;
  /** RegularExpression Id. */
  int TIMEZONE = 91;
  /** RegularExpression Id. */
  int TZ = 92;
  /** RegularExpression Id. */
  int NOW = 93;
  /** RegularExpression Id. */
  int UUID = 94;
  /** RegularExpression Id. */
  int STRUUID = 95;
  /** RegularExpression Id. */
  int TRUE = 96;
  /** RegularExpression Id. */
  int FALSE = 97;
  /** RegularExpression Id. */
  int DIGITS = 98;
  /** RegularExpression Id. */
  int INTEGER = 99;
  /** RegularExpression Id. */
  int DECIMAL = 100;
  /** RegularExpression Id. */
  int DOUBLE = 101;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 102;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 103;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 104;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 105;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 106;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 107;
  /** RegularExpression Id. */
  int EXPONENT = 108;
  /** RegularExpression Id. */
  int QUOTE_3D = 109;
  /** RegularExpression Id. */
  int QUOTE_3S = 110;
  /** RegularExpression Id. */
  int ECHAR = 111;
  /** RegularExpression Id. */
  int UCHAR = 112;
  /** RegularExpression Id. */
  int UCHAR4 = 113;
  /** RegularExpression Id. */
  int UCHAR8 = 114;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 115;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 116;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 117;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 118;
  /** RegularExpression Id. */
  int LPAREN = 119;
  /** RegularExpression Id. */
  int RPAREN = 120;
  /** RegularExpression Id. */
  int NIL = 121;
  /** RegularExpression Id. */
  int LBRACE = 122;
  /** RegularExpression Id. */
  int RBRACE = 123;
  /** RegularExpression Id. */
  int LBRACKET = 124;
  /** RegularExpression Id. */
  int RBRACKET = 125;
  /** RegularExpression Id. */
  int ANON = 126;
  /** RegularExpression Id. */
  int SEMICOLON = 127;
  /** RegularExpression Id. */
  int COMMA = 128;
  /** RegularExpression Id. */
  int DOT = 129;
  /** RegularExpression Id. */
  int EQ = 130;
  /** RegularExpression Id. */
  int NE = 131;
  /** RegularExpression Id. */
  int GT = 132;
  /** RegularExpression Id. */
  int LT = 133;
  /** RegularExpression Id. */
  int LE = 134;
  /** RegularExpression Id. */
  int GE = 135;
  /** RegularExpression Id. */
  int L_TRIPLE = 136;
  /** RegularExpression Id. */
  int R_TRIPLE = 137;
  /** RegularExpression Id. */
  int LT2 = 138;
  /** RegularExpression Id. */
  int GT2 = 139;
  /** RegularExpression Id. */
  int L_ANN = 140;
  /** RegularExpression Id. */
  int R_ANN = 141;
  /** RegularExpression Id. */
  int TILDE = 142;
  /** RegularExpression Id. */
  int BANG = 143;
  /** RegularExpression Id. */
  int COLON = 144;
  /** RegularExpression Id. */
  int SC_OR = 145;
  /** RegularExpression Id. */
  int SC_AND = 146;
  /** RegularExpression Id. */
  int PLUS = 147;
  /** RegularExpression Id. */
  int MINUS = 148;
  /** RegularExpression Id. */
  int STAR = 149;
  /** RegularExpression Id. */
  int SLASH = 150;
  /** RegularExpression Id. */
  int DATATYPE = 151;
  /** RegularExpression Id. */
  int AT = 152;
  /** RegularExpression Id. */
  int CARAT = 153;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 154;
  /** RegularExpression Id. */
  int PN_CHARS_U = 155;
  /** RegularExpression Id. */
  int PN_CHARS = 156;
  /** RegularExpression Id. */
  int PN_PREFIX = 157;
  /** RegularExpression Id. */
  int PN_LOCAL = 158;
  /** RegularExpression Id. */
  int VARNAME = 159;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 160;
  /** RegularExpression Id. */
  int PLX = 161;
  /** RegularExpression Id. */
  int HEX = 162;
  /** RegularExpression Id. */
  int PERCENT = 163;
  /** RegularExpression Id. */
  int UNKNOWN = 164;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "\"\\ufeff\"",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"$\"",
    "<LANG_DIR>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"rule\"",
    "\"then\"",
    "\"tuple\"",
    "\"data\"",
    "\"infer\"",
    "\"transitive\"",
    "\"symmetric\"",
    "\"inverse\"",
    "\"imports\"",
    "\"base\"",
    "\"prefix\"",
    "\"version\"",
    "\"where\"",
    "\"bind\"",
    "\"as\"",
    "\"let\"",
    "\":=\"",
    "\"TRIPLE\"",
    "\"isTRIPLE\"",
    "\"SUBJECT\"",
    "\"PREDICATE\"",
    "\"OBJECT\"",
    "\"EXISTS\"",
    "\"not\"",
    "\"filter\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"str\"",
    "\"strlang\"",
    "\"strlangdir\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"langdir\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"hasLang\"",
    "\"hasLangDir\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"sameValue\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<<(\"",
    "\")>>\"",
    "\"<<\"",
    "\">>\"",
    "\"{|\"",
    "\"|}\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\"^\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
