/* Generated By:JavaCC: Do not edit this line. JenaRulesJavaccConstants.java */
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */
package org.seaborne.jena.shacl_rules.lang.parser.jena_rules.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JenaRulesJavaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int BOM = 9;
  /** RegularExpression Id. */
  int IRIref = 10;
  /** RegularExpression Id. */
  int PNAME_NS = 11;
  /** RegularExpression Id. */
  int PNAME_LN = 12;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 13;
  /** RegularExpression Id. */
  int VAR1 = 14;
  /** RegularExpression Id. */
  int VAR2 = 15;
  /** RegularExpression Id. */
  int DOLLAR = 16;
  /** RegularExpression Id. */
  int LANG_DIR = 17;
  /** RegularExpression Id. */
  int A2Z = 18;
  /** RegularExpression Id. */
  int A2ZN = 19;
  /** RegularExpression Id. */
  int KW_A = 20;
  /** RegularExpression Id. */
  int RULE = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int TUPLE = 23;
  /** RegularExpression Id. */
  int TUPLES = 24;
  /** RegularExpression Id. */
  int DATA = 25;
  /** RegularExpression Id. */
  int INFER = 26;
  /** RegularExpression Id. */
  int TRANSITIVE = 27;
  /** RegularExpression Id. */
  int SYMMETRIC = 28;
  /** RegularExpression Id. */
  int INVERSE = 29;
  /** RegularExpression Id. */
  int IMPORTS = 30;
  /** RegularExpression Id. */
  int BASE = 31;
  /** RegularExpression Id. */
  int PREFIX = 32;
  /** RegularExpression Id. */
  int VERSION = 33;
  /** RegularExpression Id. */
  int WHERE = 34;
  /** RegularExpression Id. */
  int SET = 35;
  /** RegularExpression Id. */
  int FOR = 36;
  /** RegularExpression Id. */
  int LET = 37;
  /** RegularExpression Id. */
  int ASSIGN = 38;
  /** RegularExpression Id. */
  int TRIPLE = 39;
  /** RegularExpression Id. */
  int IS_TRIPLE = 40;
  /** RegularExpression Id. */
  int SUBJECT = 41;
  /** RegularExpression Id. */
  int PREDICATE = 42;
  /** RegularExpression Id. */
  int OBJECT = 43;
  /** RegularExpression Id. */
  int EXISTS = 44;
  /** RegularExpression Id. */
  int NOT = 45;
  /** RegularExpression Id. */
  int FILTER = 46;
  /** RegularExpression Id. */
  int IN = 47;
  /** RegularExpression Id. */
  int IF = 48;
  /** RegularExpression Id. */
  int BNODE = 49;
  /** RegularExpression Id. */
  int IRI = 50;
  /** RegularExpression Id. */
  int URI = 51;
  /** RegularExpression Id. */
  int STR = 52;
  /** RegularExpression Id. */
  int STRLANG = 53;
  /** RegularExpression Id. */
  int STRLANGDIR = 54;
  /** RegularExpression Id. */
  int STRDT = 55;
  /** RegularExpression Id. */
  int DTYPE = 56;
  /** RegularExpression Id. */
  int LANG = 57;
  /** RegularExpression Id. */
  int LANGMATCHES = 58;
  /** RegularExpression Id. */
  int LANGDIR = 59;
  /** RegularExpression Id. */
  int IS_URI = 60;
  /** RegularExpression Id. */
  int IS_IRI = 61;
  /** RegularExpression Id. */
  int IS_BLANK = 62;
  /** RegularExpression Id. */
  int IS_LITERAL = 63;
  /** RegularExpression Id. */
  int IS_NUMERIC = 64;
  /** RegularExpression Id. */
  int HAS_LANG = 65;
  /** RegularExpression Id. */
  int HAS_LANGDIR = 66;
  /** RegularExpression Id. */
  int REGEX = 67;
  /** RegularExpression Id. */
  int SAME_TERM = 68;
  /** RegularExpression Id. */
  int SAME_VALUE = 69;
  /** RegularExpression Id. */
  int ABS = 70;
  /** RegularExpression Id. */
  int CEIL = 71;
  /** RegularExpression Id. */
  int FLOOR = 72;
  /** RegularExpression Id. */
  int ROUND = 73;
  /** RegularExpression Id. */
  int MOD = 74;
  /** RegularExpression Id. */
  int IDIV = 75;
  /** RegularExpression Id. */
  int CONCAT = 76;
  /** RegularExpression Id. */
  int SUBSTR = 77;
  /** RegularExpression Id. */
  int STRLEN = 78;
  /** RegularExpression Id. */
  int REPLACE = 79;
  /** RegularExpression Id. */
  int UCASE = 80;
  /** RegularExpression Id. */
  int LCASE = 81;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 82;
  /** RegularExpression Id. */
  int CONTAINS = 83;
  /** RegularExpression Id. */
  int STRSTARTS = 84;
  /** RegularExpression Id. */
  int STRENDS = 85;
  /** RegularExpression Id. */
  int STRBEFORE = 86;
  /** RegularExpression Id. */
  int STRAFTER = 87;
  /** RegularExpression Id. */
  int YEAR = 88;
  /** RegularExpression Id. */
  int MONTH = 89;
  /** RegularExpression Id. */
  int DAY = 90;
  /** RegularExpression Id. */
  int HOURS = 91;
  /** RegularExpression Id. */
  int MINUTES = 92;
  /** RegularExpression Id. */
  int SECONDS = 93;
  /** RegularExpression Id. */
  int TIMEZONE = 94;
  /** RegularExpression Id. */
  int TZ = 95;
  /** RegularExpression Id. */
  int NOW = 96;
  /** RegularExpression Id. */
  int UUID = 97;
  /** RegularExpression Id. */
  int STRUUID = 98;
  /** RegularExpression Id. */
  int TRUE = 99;
  /** RegularExpression Id. */
  int FALSE = 100;
  /** RegularExpression Id. */
  int DIGITS = 101;
  /** RegularExpression Id. */
  int INTEGER = 102;
  /** RegularExpression Id. */
  int DECIMAL = 103;
  /** RegularExpression Id. */
  int DOUBLE = 104;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 105;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 106;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 107;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 108;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 109;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 110;
  /** RegularExpression Id. */
  int EXPONENT = 111;
  /** RegularExpression Id. */
  int QUOTE_3D = 112;
  /** RegularExpression Id. */
  int QUOTE_3S = 113;
  /** RegularExpression Id. */
  int ECHAR = 114;
  /** RegularExpression Id. */
  int UCHAR = 115;
  /** RegularExpression Id. */
  int UCHAR4 = 116;
  /** RegularExpression Id. */
  int UCHAR8 = 117;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 118;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 119;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 120;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 121;
  /** RegularExpression Id. */
  int LPAREN = 122;
  /** RegularExpression Id. */
  int RPAREN = 123;
  /** RegularExpression Id. */
  int NIL = 124;
  /** RegularExpression Id. */
  int LBRACE = 125;
  /** RegularExpression Id. */
  int RBRACE = 126;
  /** RegularExpression Id. */
  int LBRACKET = 127;
  /** RegularExpression Id. */
  int RBRACKET = 128;
  /** RegularExpression Id. */
  int ANON = 129;
  /** RegularExpression Id. */
  int SEMICOLON = 130;
  /** RegularExpression Id. */
  int COMMA = 131;
  /** RegularExpression Id. */
  int DOT = 132;
  /** RegularExpression Id. */
  int EQ = 133;
  /** RegularExpression Id. */
  int NE = 134;
  /** RegularExpression Id. */
  int GT = 135;
  /** RegularExpression Id. */
  int LT = 136;
  /** RegularExpression Id. */
  int LE = 137;
  /** RegularExpression Id. */
  int GE = 138;
  /** RegularExpression Id. */
  int L_TRIPLE = 139;
  /** RegularExpression Id. */
  int R_TRIPLE = 140;
  /** RegularExpression Id. */
  int LT2 = 141;
  /** RegularExpression Id. */
  int GT2 = 142;
  /** RegularExpression Id. */
  int L_ANN = 143;
  /** RegularExpression Id. */
  int R_ANN = 144;
  /** RegularExpression Id. */
  int TILDE = 145;
  /** RegularExpression Id. */
  int BANG = 146;
  /** RegularExpression Id. */
  int COLON = 147;
  /** RegularExpression Id. */
  int SC_OR = 148;
  /** RegularExpression Id. */
  int SC_AND = 149;
  /** RegularExpression Id. */
  int PLUS = 150;
  /** RegularExpression Id. */
  int MINUS = 151;
  /** RegularExpression Id. */
  int STAR = 152;
  /** RegularExpression Id. */
  int SLASH = 153;
  /** RegularExpression Id. */
  int DATATYPE = 154;
  /** RegularExpression Id. */
  int AT = 155;
  /** RegularExpression Id. */
  int CARAT = 156;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 157;
  /** RegularExpression Id. */
  int PN_CHARS_U = 158;
  /** RegularExpression Id. */
  int PN_CHARS = 159;
  /** RegularExpression Id. */
  int PN_PREFIX = 160;
  /** RegularExpression Id. */
  int PN_LOCAL = 161;
  /** RegularExpression Id. */
  int VARNAME = 162;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 163;
  /** RegularExpression Id. */
  int PLX = 164;
  /** RegularExpression Id. */
  int HEX = 165;
  /** RegularExpression Id. */
  int PERCENT = 166;
  /** RegularExpression Id. */
  int UNKNOWN = 167;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "\"\\ufeff\"",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "\"$\"",
    "<LANG_DIR>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"rule\"",
    "\"then\"",
    "\"tuple\"",
    "\"tuples\"",
    "\"data\"",
    "\"infer\"",
    "\"transitive\"",
    "\"symmetric\"",
    "\"inverse\"",
    "\"imports\"",
    "\"base\"",
    "\"prefix\"",
    "\"version\"",
    "\"where\"",
    "\"set\"",
    "\"for\"",
    "\"let\"",
    "\":=\"",
    "\"TRIPLE\"",
    "\"isTRIPLE\"",
    "\"SUBJECT\"",
    "\"PREDICATE\"",
    "\"OBJECT\"",
    "\"EXISTS\"",
    "\"not\"",
    "\"filter\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"str\"",
    "\"strlang\"",
    "\"strlangdir\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"langdir\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"hasLang\"",
    "\"hasLangDir\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"sameValue\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"MOD\"",
    "\"IDIV\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<<(\"",
    "\")>>\"",
    "\"<<\"",
    "\">>\"",
    "\"{|\"",
    "\"|}\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\"^\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
