#!/bin/bash

DIR="/home/afs/ASF/Rules/jena-rules"
JCP="$(jena CP)"
RCP="$DIR/target/classes:$DIR/target/test-classes"
CP="$RCP:$JCP"

exec java -cp "$CP" org.seaborne.jena.shacl_rules.junit.rulestests "$@"
