#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

OUT='rules-grammar.html'

echo "Grammar toHTML ($OUT)"

(
    echo "      <!-- GRAMMAR -->"
    jj2html 'shacl-rules-12.txt' 'tokens.txt'
    echo "      <!-- GRAMMAR -->"
) > $OUT
