#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

OUT='rules-grammar.bnf'

echo "Grammar to BNF ($OUT)"

(
    jj2bnf 'shacl-rules.txt' 'tokens.txt'
    
) > $OUT
