#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

BASE="shapes-rule-language"
DEST=$HOME/W3C/SHACL/rules-shacl-wg/shacl12-rules/

## Local step names
OUT_HTML='rules-grammar.html'
OUT_BNF='rules-grammar.bnf'

echo "Grammar to HTML"

(
    echo "<!-- GRAMMAR -->"
    jj2html 'shacl-rules.txt' 'tokens.txt'
    echo "<!-- GRAMMAR -->"
) > $OUT_HTML

echo "Grammar to BNF"

(
    jj2bnf 'shacl-rules.txt' 'tokens.txt'
) > $OUT_BNF

# To spec

cp $OUT_HTML "${DEST}/${BASE}.html"
cp $OUT_BNF "${DEST}/${BASE}.bnf"
