#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

BASE="sparql-rl-grammar"
DEST="$HOME/W3C/SHACL/rules-shacl-wg/sparql12-rl/"

## Local step names
OUT_HTML='sparql-rl-grammar.html'
OUT_BNF='sparql-rl-grammar.bnf'

echo "Grammar to HTML"

(
    echo "<!-- GRAMMAR -->"
    jj2html 'sparql-rl.txt' 'tokens.txt'
    echo "<!-- GRAMMAR -->"
) > $OUT_HTML

echo "Grammar to BNF"

(
    jj2bnf 'sparql-rl.txt' 'tokens.txt'
) > $OUT_BNF

# To spec

cp $OUT_HTML "${DEST}/${BASE}.html"
cp $OUT_BNF "${DEST}/${BASE}.bnf"
