#!/usr/bin/bash
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
##   SPDX-License-Identifier: Apache-2.0

GRAMMAR="${GRAMMAR:-main-shacl-rules.jj}"

# --------------------------------------------------------

function grammar
{
    FILE="$1"
    PKG="$2"
    CLASS="$3"

##     NAME="$(echo $N | tr '[:lower:]' '[:upper:]')"
##     DIR1="$(echo $N | tr '[:upper:]' '[:lower:]')"
    
    DIR="../src/main/java/org/seaborne/jena/shacl_rules/lang/parser/$PKG/javacc"
    rm -rf $DIR
    mkdir -p $DIR

    echo "---- Process grammar -- $1"
    javacc -OUTPUT_DIRECTORY=$DIR  -JDK_VERSION=1.17 "${FILE}"
    RC=$?

    [ "$RC" = 0 ] || return

##     echo "---- Create HTML"
##     jjdoc -OUTPUT_FILE=${FILE%%.jj}.html "${FILE}"
    
    echo "---- Create text form"
    jjdoc -TEXT=true -OUTPUT_FILE=${FILE%%.jj}.txt "${FILE}"

    ## ---- Fixups
    
    # Fix unnecessary imports
    echo "---- Fixing Java warnings in ${NAME}TokenManager ..."

    F="$DIR/${CLASS}TokenManager.java"

    sed -e 's/@SuppressWarnings."unused".//' \
        -e 's/import .*//' -e 's/MatchLoop: do/do/' \
        -e 's/int hiByte = (int)(curChar/int hiByte = (curChar/' \
	< $F > F
    mv F $F

    ## SimpleCharStream.
    F="$DIR/SimpleCharStream.java"
     if [ -e "$F" ]
     then
##  	 echo "---- Fixing Javadoc warnings in SimpleCharStream..."
##  	 perl -0777 -pe 's!/\*\* (Constructor|Reinitialise).!/\* $1!sg' < $F > F
	 echo "---- Fix deprecation warnings in SimpleCharStream ..."
	 echo $F
	 sed -E -e 's/public int get(Column|Line)/@Deprecated\n  &/' < $F > F 	 
 	 mv F $F
     fi
    

##     ## TokenMgrError
##     echo "---- Fixing Java warnings in TokenMgrError"
##     F="$DIR/TokenMgrError.java"
##     if [ -e "$F" ]
##     then
## 	sed -e 's/public class TokenMgrError/\n@SuppressWarnings("all")\npublic class TokenMgrError/' < $F > F 
## 	mv F $F
##     fi

    ## -- In the parser itself
    echo "---- Fixing Java warnings in ${CLASS} ..."
    F="$DIR/${CLASS}.java"
    sed -e 's/public class /\n@SuppressWarnings("all")\npublic class /' < $F > F
    mv F $F
    echo "---- Done"
}

# --------------------------------------------------------

## Grammar names
##  shacl_rules
##  jena_rules

if [ $# == 0 ]
then
    set -- shacl_rules jena_rules
    ## echo "Usage: grammar [jena_rules|shacl_rules]" 1>&2
    ## exit 1
fi

## -P : No line markers
## -C : Keep comments
## -nostdinc : No (C standard) incldues searching
CPP_ARGS="-P -C -nostdinc"

for G in "$@"
do
  case "$G" in
      shacl_rules)
          # The parser that is exactly the working group grammar.
          cat "$GRAMMAR" | cpp $CPP_ARGS -DSTD - > shacl-rules.jj
          grammar shacl-rules.jj shacl_rules ShaclRulesJavacc
          ;;

      jena_rules)
          cat "$GRAMMAR" | cpp $CPP_ARGS -DJENA - > jena-rules.jj
          grammar jena-rules.jj jena_rules JenaRulesJavacc
          ;;

      *)    echo "**** Unknown grammar: $G" 1>&2
            ;;
    esac
done
