[1]    RuleSet                   ::= RuleOrDataBlock
[2]    RuleOrDataBlock           ::= Prologue ( RuleOrData+ ( Prologue1 RuleOrData? )* )?
[3]    RuleOrData                ::= Rule | Data
[4]    Prologue                  ::= Prologue1*
[5]    Prologue1                 ::= BaseDecl | PrefixDecl | VersionDecl | ImportsDecl
[6]    BaseDecl                  ::= 'BASE' IRIREF
[7]    PrefixDecl                ::= 'PREFIX' PNAME_NS IRIREF
[8]    VersionDecl               ::= 'VERSION' VersionSpecifier
[9]    VersionSpecifier          ::= STRING_LITERAL1 | STRING_LITERAL2
[10]   ImportsDecl               ::= 'IMPORTS' iri
[11]   Rule                      ::= Rule1 | Rule2 | Declaration
[12]   Rule1                     ::= 'RULE' iri? HeadTemplate 'WHERE' BodyPattern
[13]   Rule2                     ::= 'IF' BodyPattern 'THEN' HeadTemplate
[14]   Data                      ::= 'DATA' '{' DataTriplesBlock? '}'
[15]   HeadTemplate              ::= '{' HeadTemplateBlock? '}'
[16]   BodyPattern               ::= '{' BodyTriplesBlock? ( BodyNotTriples '.'? BodyTriplesBlock? )* '}'
[17]   BodyNotTriples            ::= Filter | Negation | Assignment
[18]   Filter                    ::= 'FILTER' Constraint
[19]   Constraint                ::= BrackettedExpression | BuiltInCall | FunctionCall
[20]   FunctionCall              ::= iri ArgList
[21]   ArgList                   ::= NIL | '(' Expression ( ',' Expression )* ')' 
[22]   ExpressionList            ::= NIL | '(' Expression ( ',' Expression )* ')' 
[23]   Negation                  ::= 'NOT' '{' BodyBasic '}'
[24]   BodyBasic                 ::= BodyTriplesBlock? ( BodyBasicNotTriples '.'? BodyTriplesBlock? )*
[25]   BodyBasicNotTriples       ::= Filter
[26]   Assignment                ::= 'SET' '(' Var ':=' Expression ')'
[27]   Declaration               ::= ( 'TRANSITIVE' '(' iri ')' | '(' iri ')' 'SYMMETRIC' | 'INVERSE' '(' iri ',' iri ')' )
[28]   DataTriplesBlock          ::= TriplesSameSubjectData ( '.' DataTriplesBlock? )?
[29]   TriplesSameSubjectData    ::= RDFTermData PropertyListNotEmptyData | TriplesNodeData PropertyListData | ReifiedTripleBlockData
[30]   PropertyListData          ::= PropertyListNotEmptyData?
[31]   PropertyListNotEmptyData  ::= VerbData ObjectListData ( ';' ( VerbData ObjectListData )? )*
[32]   VerbData                  ::= iri | 'a'
[33]   ObjectListData            ::= ObjectData ( ',' ObjectData )*
[34]   ObjectData                ::= GraphNodeData AnnotationData
[35]   GraphNodeData             ::= RDFTermData | TriplesNodeData | ReifiedTripleData
[36]   TriplesNodeData           ::= CollectionData | BlankNodePropertyListData
[37]   BlankNodePropertyListData ::= '[' PropertyListNotEmptyData ']'
[38]   CollectionData            ::= '(' GraphNodeData+ ')'
[39]   AnnotationData            ::= ( ReifierData | AnnotationBlockData )*
[40]   AnnotationBlockData       ::= '{|' PropertyListNotEmptyData '|}'
[41]   ReifierData               ::= '~' ReifierIdData?
[42]   ReifierIdData             ::= iri | BlankNode
[43]   ReifiedTripleBlockData    ::= ReifiedTripleData PropertyListData
[44]   ReifiedTripleData         ::= '<<' ReifiedTripleSubjectData VerbData ReifiedTripleObjectData ReifierData? '>>'
[45]   ReifiedTripleSubjectData  ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleData | TripleTermData
[46]   ReifiedTripleObjectData   ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleData | TripleTermData
[47]   TripleTermData            ::= '<<(' TripleTermSubjectData VerbData TripleTermObjectData ')>>'
[48]   TripleTermSubjectData     ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermData
[49]   TripleTermObjectData      ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermData
[50]   HeadTemplateBlock         ::= TriplesBlockTemplate
[51]   TriplesBlockTemplate      ::= TriplesSameSubjectTemplate ( '.' TriplesBlockTemplate? )?
[52]   TriplesSameSubjectTemplate ::= VarOrRDFTerm PropertyListNotEmptyTemplate | TriplesNodeTemplate PropertyListTemplate | ReifiedTripleBlockTemplate
[53]   PropertyListTemplate      ::= PropertyListNotEmptyTemplate?
[54]   PropertyListNotEmptyTemplate ::= Verb ObjectListTemplate ( ';' ( VerbTemplate ObjectListTemplate )? )*
[55]   VerbTemplate              ::= VarOrIri | 'a'
[56]   ObjectListTemplate        ::= ObjectTemplate ( ',' ObjectTemplate )*
[57]   ObjectTemplate            ::= GraphNodeTemplate AnnotationTemplate
[58]   GraphNodeTemplate         ::= VarOrRDFTerm | TriplesNodeTemplate | ReifiedTripleTemplate
[59]   TriplesNodeTemplate       ::= CollectionTemplate | BlankNodePropertyListTemplate
[60]   BlankNodePropertyListTemplate ::= '[' PropertyListNotEmptyTemplate ']'
[61]   CollectionTemplate        ::= '(' GraphNodeTemplate+ ')'
[62]   AnnotationTemplate        ::= ( ReifierTemplate | AnnotationBlockTemplate )*
[63]   AnnotationBlockTemplate   ::= '{|' PropertyListNotEmptyTemplate '|}'
[64]   ReifierTemplate           ::= '~' ReifierIdTemplate?
[65]   ReifierIdTemplate         ::= Var | iri | BlankNode
[66]   ReifiedTripleBlockTemplate ::= ReifiedTripleTemplate PropertyListTemplate
[67]   ReifiedTripleTemplate     ::= '<<' ReifiedTripleSubjectTemplate VerbTemplate ReifiedTripleObjectTemplate ReifierTemplate? '>>'
[68]   ReifiedTripleSubjectTemplate ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleTemplate | TripleTermTemplate
[69]   ReifiedTripleObjectTemplate ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTripleTemplate | TripleTermTemplate
[70]   TripleTermTemplate        ::= '<<(' TripleTermSubjectTemplate VerbTemplate TripleTermObjectTemplate ')>>'
[71]   TripleTermSubjectTemplate ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermTemplate
[72]   TripleTermObjectTemplate  ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermTemplate
[73]   BodyTriplesBlock          ::= TriplesBlockPattern
[74]   TriplesBlockPattern       ::= TriplesSameSubjectPattern ( '.' TriplesBlockPattern? )?
[75]   ReifiedTripleBlockPattern ::= ReifiedTriplePattern PropertyListPattern
[76]   ReifierPattern            ::= '~' ReifierIdPattern?
[77]   ReifierIdPattern          ::= Var | iri | BlankNode
[78]   TriplesSameSubjectPattern ::= VarOrRDFTerm PropertyListNotEmptyPattern | TriplesNodePattern PropertyListPattern | ReifiedTripleBlockPattern
[79]   PropertyListPattern       ::= PropertyListNotEmptyPattern?
[80]   PropertyListNotEmptyPattern ::= ( VerbPath | VerbVar ) ObjectListPattern ( ';' ( ( VerbPath | VerbVar ) ObjectListPattern )? )*
[81]   ObjectListPattern         ::= ObjectPattern ( ',' ObjectPattern )*
[82]   ObjectPattern             ::= GraphNodePattern AnnotationPattern
[83]   TriplesNodePattern        ::= CollectionPattern | BlankNodePropertyListPattern
[84]   BlankNodePropertyListPattern ::= '[' PropertyListNotEmptyPattern ']'
[85]   CollectionPattern         ::= '(' GraphNodePattern+ ')'
[86]   AnnotationPattern         ::= ( ReifierPattern | AnnotationBlockPattern )*
[87]   AnnotationBlockPattern    ::= '{|' PropertyListNotEmptyPattern '|}'
[88]   GraphNodePattern          ::= VarOrRDFTerm | TriplesNodePattern | ReifiedTriplePattern
[89]   ReifiedTriplePattern      ::= '<<' ReifiedTripleSubjectPattern Verb ReifiedTripleObjectPattern ReifierPattern? '>>'
[90]   ReifiedTripleSubjectPattern ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTriplePattern | TripleTermPattern
[91]   ReifiedTripleObjectPattern ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | ReifiedTriplePattern | TripleTermPattern
[92]   TripleTermPattern         ::= '<<(' TripleTermSubjectPattern Verb TripleTermObjectPattern ')>>'
[93]   TripleTermSubjectPattern  ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermPattern
[94]   TripleTermObjectPattern   ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | TripleTermPattern
[95]   Verb                      ::= VarOrIri | 'a'
[96]   VerbPath                  ::= Path
[97]   VerbVar                   ::= Var
[98]   Path                      ::= PathSequence
[99]   PathSequence              ::= PathEltOrInverse ( '/' PathEltOrInverse )*
[100]  PathEltOrInverse          ::= PathElt | '^' PathElt
[101]  PathElt                   ::= ( iri | 'a' | '(' Path ')' )
[102]  RDFTermData               ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | NIL | TripleTermData
[103]  VarOrRDFTerm              ::= Var | iri | RDFLiteral | NumericLiteral | BooleanLiteral | BlankNode | NIL | TripleTermPattern
[104]  VarOrIri                  ::= Var | iri
[105]  Var                       ::= VAR1 | VAR2
[106]  RDFLiteral                ::= String ( LANG_DIR | '^^' iri )?
[107]  Expression                ::= ConditionalOrExpression
[108]  ConditionalOrExpression   ::= ConditionalAndExpression ( '||' ConditionalAndExpression )*
[109]  ConditionalAndExpression  ::= ValueLogical ( '&&' ValueLogical )*
[110]  ValueLogical              ::= RelationalExpression
[111]  RelationalExpression      ::= NumericExpression ( '=' NumericExpression | '!=' NumericExpression | '<' NumericExpression | '>' NumericExpression | '<=' NumericExpression | '>=' NumericExpression | 'IN' ExpressionList | 'NOT' 'IN' ExpressionList )?
[112]  NumericExpression         ::= AdditiveExpression
[113]  AdditiveExpression        ::= MultiplicativeExpression ( '+' MultiplicativeExpression | '-' MultiplicativeExpression | ( NumericLiteralPositive | NumericLiteralNegative ) ( ( '*' UnaryExpression ) | ( '/' UnaryExpression ) )* )*
[114]  MultiplicativeExpression  ::= UnaryExpression ( '*' UnaryExpression | '/' UnaryExpression )*
[115]  UnaryExpression           ::= '!' PrimaryExpression 
                                   | '+' PrimaryExpression 
                                   | '-' PrimaryExpression 
                                   | PrimaryExpression
[116]  PrimaryExpression         ::= BrackettedExpression | BuiltInCall | iriOrFunction | RDFLiteral | NumericLiteral | BooleanLiteral | Var | ExprTripleTerm
[117]  ExprTripleTerm            ::= '<<(' ExprTripleTermSubject Verb ExprTripleTermObject ')>>'
[118]  ExprTripleTermSubject     ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | Var
[119]  ExprTripleTermObject      ::= iri | RDFLiteral | NumericLiteral | BooleanLiteral | Var | ExprTripleTerm
[120]  BrackettedExpression      ::= '(' Expression ')'
[121]  BuiltInCall               ::= 'STR' '(' Expression ')' 
                                   | 'LANG' '(' Expression ')' 
                                   | 'LANGMATCHES' '(' Expression ',' Expression ')' 
                                   | 'LANGDIR' '(' Expression ')' 
                                   | 'DATATYPE' '(' Expression ')' 
                                   | 'IRI' '(' Expression ')' 
                                   | 'URI' '(' Expression ')' 
                                   | 'BNODE' ( '(' Expression ')' | NIL ) 
                                   | 'ABS' '(' Expression ')' 
                                   | 'CEIL' '(' Expression ')' 
                                   | 'FLOOR' '(' Expression ')' 
                                   | 'ROUND' '(' Expression ')' 
                                   | 'CONCAT' ExpressionList 
                                   | 'SUBSTR' '(' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'STRLEN' '(' Expression ')' 
                                   | 'REPLACE' '(' Expression ',' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'UCASE' '(' Expression ')' 
                                   | 'LCASE' '(' Expression ')' 
                                   | 'ENCODE_FOR_URI' '(' Expression ')' 
                                   | 'CONTAINS' '(' Expression ',' Expression ')' 
                                   | 'STRSTARTS' '(' Expression ',' Expression ')' 
                                   | 'STRENDS' '(' Expression ',' Expression ')' 
                                   | 'STRBEFORE' '(' Expression ',' Expression ')' 
                                   | 'STRAFTER' '(' Expression ',' Expression ')' 
                                   | 'YEAR' '(' Expression ')' 
                                   | 'MONTH' '(' Expression ')' 
                                   | 'DAY' '(' Expression ')' 
                                   | 'HOURS' '(' Expression ')' 
                                   | 'MINUTES' '(' Expression ')' 
                                   | 'SECONDS' '(' Expression ')' 
                                   | 'TIMEZONE' '(' Expression ')' 
                                   | 'TZ' '(' Expression ')' 
                                   | 'NOW' NIL 
                                   | 'UUID' NIL 
                                   | 'STRUUID' NIL 
                                   | 'IF' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'STRLANG' '(' Expression ',' Expression ')' 
                                   | 'STRLANGDIR' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'STRDT' '(' Expression ',' Expression ')' 
                                   | 'sameTerm' '(' Expression ',' Expression ')' 
                                   | 'isIRI' '(' Expression ')' 
                                   | 'isURI' '(' Expression ')' 
                                   | 'isBLANK' '(' Expression ')' 
                                   | 'isLITERAL' '(' Expression ')' 
                                   | 'isNUMERIC' '(' Expression ')' 
                                   | 'hasLANG' '(' Expression ')' 
                                   | 'hasLANGDIR' '(' Expression ')' 
                                   | 'REGEX' '(' Expression ',' Expression ( ',' Expression )? ')' 
                                   | 'isTRIPLE' '(' Expression ')' 
                                   | 'TRIPLE' '(' Expression ',' Expression ',' Expression ')' 
                                   | 'SUBJECT' '(' Expression ')' 
                                   | 'PREDICATE' '(' Expression ')' 
                                   | 'OBJECT' '(' Expression ')'
[122]  iriOrFunction             ::= iri ArgList?
[123]  NumericLiteral            ::= NumericLiteralUnsigned | NumericLiteralPositive | NumericLiteralNegative
[124]  NumericLiteralUnsigned    ::= INTEGER | DECIMAL | DOUBLE
[125]  NumericLiteralPositive    ::= INTEGER_POSITIVE | DECIMAL_POSITIVE | DOUBLE_POSITIVE
[126]  NumericLiteralNegative    ::= INTEGER_NEGATIVE | DECIMAL_NEGATIVE | DOUBLE_NEGATIVE
[127]  BooleanLiteral            ::= 'true' | 'false'
[128]  String                    ::= STRING_LITERAL1 | STRING_LITERAL2 | STRING_LITERAL_LONG1 | STRING_LITERAL_LONG2
[129]  iri                       ::= IRIREF | PrefixedName
[130]  PrefixedName              ::= PNAME_LN | PNAME_NS
[131]  BlankNode                 ::= BLANK_NODE_LABEL | ANON

@terminals

[132]  IRIREF                    ::= '<' ([^<>"{}|^`\]-[#x00-#x20] | UCHAR )* '>'
[133]  PNAME_NS                  ::= PN_PREFIX? ':'
[134]  PNAME_LN                  ::= PNAME_NS PN_LOCAL
[135]  BLANK_NODE_LABEL          ::= '_:' ( PN_CHARS_U | [0-9] ) ((PN_CHARS|'.')* PN_CHARS)?
[136]  VAR1                      ::= '?' VARNAME
[137]  VAR2                      ::= '$' VARNAME
[138]  LANG_DIR                  ::= '@' [a-zA-Z]+ ('-' [a-zA-Z0-9]+)* ('--' [a-zA-Z]+)?
[139]  INTEGER                   ::= [0-9]+
[140]  DECIMAL                   ::= [0-9]* '.' [0-9]+
[141]  DOUBLE                    ::= ( ([0-9]+ ('.'[0-9]*)? ) | ( '.' ([0-9])+ ) ) [eE][+-]?[0-9]+
[142]  INTEGER_POSITIVE          ::= '+' INTEGER
[143]  DECIMAL_POSITIVE          ::= '+' DECIMAL
[144]  DOUBLE_POSITIVE           ::= '+' DOUBLE
[145]  INTEGER_NEGATIVE          ::= '-' INTEGER
[146]  DECIMAL_NEGATIVE          ::= '-' DECIMAL
[147]  DOUBLE_NEGATIVE           ::= '-' DOUBLE
[148]  STRING_LITERAL1           ::= "'" ( ([^#x27#x5C#xA#xD]) | ECHAR | UCHAR )* "'"
[149]  STRING_LITERAL2           ::= '"' ( ([^#x22#x5C#xA#xD]) | ECHAR | UCHAR )* '"'
[150]  STRING_LITERAL_LONG1      ::= "'''" ( ( "'" | "''" )? ( [^'\] | ECHAR | UCHAR ) )* "'''"
[151]  STRING_LITERAL_LONG2      ::= '"""' ( ( '"' | '""' )? ( [^"\] | ECHAR | UCHAR ) )* '"""'
[152]  ECHAR                     ::= '\' [tbnrf\"']
[153]  UCHAR                     ::= ('\u' HEX HEX HEX HEX) | ('\U' HEX HEX HEX HEX HEX HEX HEX HEX)
[154]  NIL                       ::= '(' WS* ')'
[155]  WS                        ::= #x20 | #x9 | #xD | #xA
[156]  ANON                      ::= '['  WS* ']'
[157]  PN_CHARS_BASE             ::= [A-Z] 
                                   | [a-z] 
                                   | [#x00C0-#x00D6] 
                                   | [#x00D8-#x00F6] 
                                   | [#x00F8-#x02FF] 
                                   | [#x0370-#x037D] 
                                   | [#x037F-#x1FFF] 
                                   | [#x200C-#x200D] 
                                   | [#x2070-#x218F] 
                                   | [#x2C00-#x2FEF] 
                                   | [#x3001-#xD7FF] 
                                   | [#xF900-#xFDCF] 
                                   | [#xFDF0-#xFFFD] 
                                   | [#x10000-#xEFFFF]
[158]  PN_CHARS_U                ::= PN_CHARS_BASE | '_'
[159]  VARNAME                   ::= ( PN_CHARS_U  | [0-9] ) ( PN_CHARS_U | [0-9] | #x00B7 | [#x0300-#x036F] | [#x203F-#x2040] )*
[160]  PN_CHARS                  ::= PN_CHARS_U | '-' | [0-9] | #x00B7 | [#x0300-#x036F] | [#x203F-#x2040]
[161]  PN_PREFIX                 ::= PN_CHARS_BASE ((PN_CHARS|'.')* PN_CHARS)?
[162]  PN_LOCAL                  ::= (PN_CHARS_U | ':' | [0-9] | PLX ) ((PN_CHARS | '.' | ':' | PLX)* (PN_CHARS | ':' | PLX) )?
[163]  PLX                       ::= PERCENT | PN_LOCAL_ESC
[164]  PERCENT                   ::= '%' HEX HEX
[165]  HEX                       ::= [0-9] | [A-F] | [a-f]
[166]  PN_LOCAL_ESC              ::= '\' ( '_' | '~' | '.' | '-' | '!' | '$' | '&' | "'" | '(' | ')' | '*' | '+' | ',' | ';' | '=' | '/' | '?' | '#' | '@' | '%' )
